### ISSUE TITLE
発表までにやることリスト

### ISSUE THREAD

**Issue by suguru-toyohara** [tech-creative-club/tama-river-client#32]
### todo

- [x] workerでkvの投入口を作る(ゲロ簡単) → みなぎし
- [x] workerでimagesの投入口を作る(簡単) → みなぎし
- [x] pythonで調布市スポーツイベントページを全部スクレイピングする(中程度) → 私

↑22はここまで

- [x] workerにkvデータ送信するPython書く(簡単)
- [x] ~workerに画像データを送信するpython書く(中程度)~ →間に合わないのでよい
- [x] workerからkv排出口を作る(ゲロ簡単)
- [x] clientからkv排出口workerを叩く(簡単)
- [x] clientからworkerでkvを読んで表示させる機能を作成する(ムズイ)
- [x] ~clientからworker経由でimageを読む機能を作成する(簡単)~ →間に合わないのでよい

**Comment by minagishl** [comment]
- [workerでkvの投入口を作る](https://github.com/tech-creative-club/tama-river-client/pull/33)

**Comment by suguru-toyohara** [comment]
### 17時までにやること

みなぎし
- [ ] インラインコメントTODO消化

すぐる
- [ ] python書き散らす
- [ ]

**Comment by suguru-toyohara** [comment]
All DONE
